services:
  app:
    build:
      context: ./talabalocation
    container_name: talabalocation_app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - talabalocation
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: talabalocation_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: talabalocation
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
    ports:
      - "3311:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - talabalocation

  nginx:
    image: nginx:alpine
    container_name: talabalocation_nginx
    ports:
      - "8011:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/html
    depends_on:
      - app
    networks:
      - talabalocation

volumes:
  dbdata:

networks:
  talabalocation:

